export const userTypes = {
  USER_LOGIN_STARTED: "USER_LOGIN_STARTED",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_DATA_FETCH_STARTED: "USER_DATA_FETCH_STARTED",
  USER_DATA_FETCH_SUCCESS: "USER_DATA_FETCH_SUCCESS",
  USER_DATA_FETCH_FAILED: "USER_DATA_FETCH_FAILED"
};

export const uiTypes = {
  SET_ERRORS: "SET_ERRORS",
  LOADING_UI: "LOADING_UI",
  CLEAR_ERRORS: "CLEAR_ERRORS"
};
