export const userTypes = {
  USER_LOGIN_STARTED: "USER_LOGIN_STARTED",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_DATA_FETCH_STARTED: "USER_DATA_FETCH_STARTED",
  USER_DATA_FETCH_SUCCESS: "USER_DATA_FETCH_SUCCESS",
  USER_DATA_FETCH_FAILED: "USER_DATA_FETCH_FAILED",
  USER_SIGNUP_STARTED: "USER_SIGNUP_STARTED",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_IMAGE_UPLOAD_STARTED: "USER_IMAGE_UPLOAD_STARTED",
  USER_IMAGE_UPLOAD_SUCCESS: "USER_IMAGE_UPLOAD_SUCCESS",
  USER_IMAGE_UPLOAD_FAILED: "USER_IMAGE_UPLOAD_FAILED",
  USER_BIO_UPDATE_STARTED: "USER_BIO_UPDATE_STARTED",
  USER_BIO_UPDATE_SUCCESS: "USER_BIO_UPDATE_SUCCESS",
  USER_BIO_UPDATE_FAILED: "USER_BIO_UPDATE_FAILED"
};
export const initTypes = {
  APP_INIT_DATA_FETCH_STARTED: "APP_INIT_DATA_FETCH_STARTED",
  APP_INIT_DATA_FETCH_SUCCESS: "APP_INIT_DATA_FETCH_SUCCESS",
  APP_INIT_DATA_FETCH_FAILED: "APP_INIT_DATA_FETCH_FAILED"
};

export const likeTypes = {
  LIKE_SCREAM: "LIKE_SCREAM",
  UNLIKE_SCREAM: "UNLIKE_SCREAM"
};

export const deleteTypes = {
  SCREAM_DELETE_STARTED: "SCREAM_DELETE_STARTED",
  SCREAM_DELETE_SUCCESS: "SCREAM_DELETE_SUCCESS",
  SCREAM_DELETE_FAILED: "SCREAM_DELETE_FAILED"
};

export const screamTypes = {
  SCREAM_ADD_STARTED: "SCREAM_ADD_STARTED",
  SCREAM_ADD_SUCCESS: "SCREAM_ADD_SUCCESS",
  SCREAM_ADD_FAILED: "SCREAM_ADD_FAILED"
};

export const fetchScreamTypes = {
  SINGLE_SCREAM_FETCH_STARTED: "SINGLE_SCREAM_FETCH_STARTED",
  SINGLE_SCREAM_FETCH_SUCCEED: "SINGLE_SCREAM_FETCH_SUCCEED",
  SINGLE_SCREAM_FETCH_FAILED: "SINGLE_SCREAM_FETCH_FAILED"
};
export const postCommentTypes = {
  POST_COMMENT_STARTED: "POST_COMMENT_STARTED",
  POST_COMMENT_SUCCESS: "POST_COMMENT_SUCCESS",
  POST_COMMENT_FAILED: "POST_COMMENT_FAILED"
};

export const profileFetch = {
  PROFILE_FETCH_STARTED: "PROFILE_FETCH_STARTED",
  USER_PROFILE_FETCH_SUCCEED: "USER_PROFILE_FETCH_SUCCEED",
  USER_SCREAM_FETCH_SUCCEED: "USER_SCREAM_FETCH_SUCCEED",
  PROFILE_FETCH_FAILED: "USER_PROFILE_FETCH_FAILED"
};
export const notificationsType = {
  MARK_NOTIFICATIONS_READ_STARTED: "MARK_NOTIFICATIONS_READ_STARTED",
  MARK_NOTIFICATIONS_READ_SUCCESS: "MARK_NOTIFICATIONS_READ_SUCCESS",
  MARK_NOTIFICATIONS_READ_FAILED: "MARK_NOTIFICATIONS_READ_FAILED"
};
